- name: Get Console plugin list
  kubernetes.core.k8s_info:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
  register: openshift_console
  until: openshift_console is not failed

- name: Append logging to console plugins list
  when:
    - openshift_console.resources[0].spec.plugins is defined
    - ("logging-view-plugin" not in openshift_console.resources[0].spec.plugins)
  kubernetes.core.k8s_json_patch:
    api_version: operator.openshift.io/v1
    kind: Console
    name: cluster
    patch:
      - op: add
        path: /spec/plugins/-
        value: logging-view-plugin
  register: k8s_result
  until: k8s_result is not failed

- name: Create console plugin list and add logging
  when: openshift_console.resources[0].spec.plugins is not defined
  kubernetes.core.k8s:
    definition:
      apiVersion: operator.openshift.io/v1
      kind: Console
      metadata:
        name: cluster
      spec:
        plugins:
          - logging-view-plugin
    state: present
  register: k8s_result
  until: k8s_result is not failed
