name: Build project
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - name: Install packages
        run: |
          dnf -q -y update
          dnf -q -y install python3-pip git
          pip3 install --upgrade pip
          pip3 install --upgrade ansible-core kubernetes ansible-lint
          ansible-galaxy collection install -U kubernetes.core community.general ansible.utils
          git config --global --add safe.directory /__w/openshift-loki-installer/openshift-loki-installer
      - uses: actions/checkout@v3
      - name: Check code
        run: |
          ansible-lint -s -x yaml[line-length],role-name
